#!/usr/bin/env python
# encoding: utf-8

BAA_SERVER_IP = '172.27.0.9'
BAA_NBI_PORT = '9292'
BAA_USERNAME = 'admin'
BAA_PASSWORD = 'password'
POLT_SIM_IP = '172.27.0.5'
ONU_SIM_IP = '172.27.0.6'
POLT_SIM_PORT = '10830'
ONU_SIM_PORT = '50000'
POLT_SIM_USER = 'root'
POLT_SIM_PASSWORD = 'root'
ALIGNED = 'Aligned'
CONNECTED_TRUE = 'true'
CONNECTED_FALSE = 'false'
OK_RESPONSE = 'ok'
BAA_REQUEST_PATH = './data/netconf_requests/'
POLT_CONTAINER_NAME = 'polt-simulator'
OLT_NAME = 'OLT'
ALIGNMENT_ERROR = '<configuration-alignment-state>In Error,'
ALIGNMENT_UNKNOWN = 'Alignment Unknown'
ONU_SIMULATOR_NAME = 'onu-simulator'
CURRENT_RELEASE = '6.0.0'
POLT_REST_URL = 'http://127.0.0.1:3002/polt/polt_actions'